version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - node.name=es01
      - cluster.name=rag-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - rag_network
    # Install IK analysis plugin on startup
    command: >
      bash -c "
      if ! elasticsearch-plugin list | grep -q analysis-ik; then
        elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.17.0
      fi &&
      /usr/local/bin/docker-entrypoint.sh eswrapper
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  huggingface-embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7.0
    environment:
      - HF_MIRROR=${HF_MIRROR:-https://hf-mirror.com}
      - HF_ENDPOINT=${HF_ENDPOINT:-https://hf-mirror.com}
      - HUGGINGFACE_HUB_CACHE=/data
      - HF_HOME=/data
      - TRANSFORMERS_CACHE=/data
    ports:
      - "8080:80"
    networks:
      - rag_network
    volumes:
      - embedding_cache:/data
    command: ["--model-id", "BAAI/bge-small-en-v1.5", "--revision", "main", "--max-concurrent-requests", "32", "--max-batch-tokens", "4096", "--port", "80", "--hostname", "0.0.0.0", "--auto-truncate"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 1.5g
        reservations:
          memory: 512m

volumes:
  embedding_cache:
    driver: local

networks:
  rag_network:
    driver: bridge
